trigger:
  branches:
    include:
    - refs/heads/master
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    clean: true
  - task: Docker@0
    displayName: Build an image
    env:
      DISCORD_TOKEN: $(DISCORD_TOKEN)
    inputs:
      azureSubscriptionEndpoint: 42a19424-02fe-48a7-a44f-effa93a336bd
      azureContainerRegistry: '{"loginServer":"discordpokebot.azurecr.io", "id" : "/subscriptions/42a19424-02fe-48a7-a44f-effa93a336bd/resourceGroups/Discordbot/providers/Microsoft.ContainerRegistry/registries/discordpokebot"}'
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: 42a19424-02fe-48a7-a44f-effa93a336bd
      azureContainerRegistry: '{"loginServer":"discordpokebot.azurecr.io", "id" : "/subscriptions/42a19424-02fe-48a7-a44f-effa93a336bd/resourceGroups/Discordbot/providers/Microsoft.ContainerRegistry/registries/discordpokebot"}'
      action: Push an image
  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.ArtifactStagingDirectory)'  
  - task: PublishBuildArtifacts@1    
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    

...
